apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: sprinter
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/idekctf-374221/sprinter-healthcheck:834d1113f16e777f7a248a6dacd49807bda96a314fcf6bb3ca3ffc28ca1a7b55
  image: us.gcr.io/idekctf-374221/sprinter-challenge:9bf030da1db82bca6700ae062e3f8b421cf19c8c61af86a3402e66a1f745c45d
