version: '2.4'
services:
  admservices:
    build: .
    ports:
      - 4000:1234
    # read_only: true
    privileged: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined

    mem_limit: 1G
    restart: on-failure